[versions]
kotlin = "1.8.0"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.7.1" }

[plugins]
google-ksp = { id = "com.google.devtools.ksp", version = "1.8.10-1.0.9" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlink-jvm = { id = "kotlink.jvm", version = "unspecified" }
kotlink-maven = { id = "kotlink.maven", version = "unspecified" }
kotlink-signing = { id = "kotlink.signing", version = "unspecified" }
